### ISSUE TITLE
problem with snapgene_reader

### ISSUE THREAD

**Issue by jurquiza** [Edinburgh-Genome-Foundry/DnaCauldron#2]
Attempting to install results in the following error for snapgene reader using pip3 

  Using cached https://files.pythonhosted.org/packages/f6/90/bfd3cc66c6e5045f4156b695708dcec715e9ff18d4aef9493fd7f966f5aa/snapgene_reader-0.1.15.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-kl5wwig5/snapgene-reader/setup.py", line 13, in <module>
        long_description=open('README.rst').read(),
      File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 1031: ordinal not in range(128)
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-kl5wwig5/snapgene-reader/

**Comment by Zulko** [comment]
Maybe it doesn't like the "¢" in the README. It doesn't do that with me but maybe it is machine-dependent (what OS are you using?).

I have edited the README on Github, could you try installing directly from Github?

```
pip3 install git+https://github.com/Edinburgh-Genome-Foundry/SnapGeneReader.git
```

If it works, you may be able to pip3 install dnacauldron normally. If not also try with Github

```
pip3 install git+https://github.com/Edinburgh-Genome-Foundry/dnacauldron.git
```

Let me know what worked and what didn't.

**Comment by jurquiza** [comment]
yes, it worked. I am using a Docker container with Ubuntu:latest. However if I try DNAcauldron first before trying snapgene_reader it still has the error. if I install snapgene_reder first then it allows me to install DNAcauldron

**Comment by Zulko** [comment]
Ok thanks for the tests, this seems to confirm that the problem was the "¢" symbol.

I have pushed the fixes to PyPI so you should be able to install simply with "pip install dnacauldron" now. Let me know if that still doesn't work.

Not sure why the problem appeared on Ubuntu:latest though (and not on any Ubuntu machine or Python docker I have tried so far).
