### ISSUE TITLE
Error after Updating Biopython

### ISSUE THREAD

**Issue by frba** [Edinburgh-Genome-Foundry/DnaCauldron#23]
I updated the biopython 1.79 to 1.84 and I got this error:

    from ..biotools import find_narrowest_text_wrap
  File "/Users/flavia/.../python3.9/site-packages/dna_features_viewer/biotools.py", line 38, in <module>
    _aa1: _aa3[0] + _aa3[1:].lower() for (_aa1, _aa3) in zip(aa1 + "*", aa3 + ["*"])
TypeError: can only concatenate tuple (not "str") to tuple

Do you happen to have a suggestion on how I could fix this?

**Comment by veghp** [comment]
This seems to be a former issue with DNA Features Viewer and it has been sorted: https://github.com/Edinburgh-Genome-Foundry/DnaFeaturesViewer/issues/73

Please update DNA Features Viewer and see if it works correctly?

**Comment by frba** [comment]
Thanks a lot, Peter! You're a lifesaver.
